name: lando-postgres-11
services:
  defaults:
    type: postgres:11
  cross:
    type: postgres:11
    portforward: true
tooling:
  healthcheckdefaults:
    service: defaults
    cmd: psql -U postgres -c "\\l"
  verifydefaultsdatabase:
    service: defaults
    cmd: psql -P pager=off -U postgres -c "\dt *.*"
  crossconnect:
    service: defaults
    cmd: psql -P pager=off -h cross -U postgres -c "\dt *.*"

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/postgres": ./../../