name: lando-postgres
services:
  custom:
    type: postgres:11
    portforward: true
    creds:
      database: trouble
    config:
      database: config/mythings.conf
  mimicarecipe:
    type: postgres
    creds:
      database: mimic
  cross:
    type: postgres:14
    portforward: true
tooling:
  verifycustom:
    service: custom
    cmd: psql -P pager=off -U postgres -c "\dt *.*"
  showmax:
    user: root
    service: custom
    cmd: psql -U postgres -c 'SHOW MAX_FILES_PER_PROCESS;'
  crossconnect:
    service: custom
    cmd: psql -P pager=off -h cross -U postgres -c "\dt *.*"

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/postgres": ./../../